# Generated by Django 3.0.3 on 2020-08-15 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=64)),
                ('thumbnail', models.ImageField(default='default_thumb.jpg', upload_to='thumbnails')),
                ('video', models.FileField(default='error.mp4', upload_to='videos')),
                ('video_url', models.CharField(default='error', max_length=255)),
                ('duration', models.CharField(default='00:00', max_length=16)),
                ('ownear', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
