# Generated by Django 3.0.3 on 2020-08-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default_thumb.jpg', upload_to='thumbnails'),
        ),
    ]
