# Generated by Django 3.0.3 on 2020-08-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(default='00:00', max_length=16),
        ),
    ]
