# Generated by Django 3.1 on 2020-08-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='error', max_length=255),
        ),
    ]
