# Generated by Django 3.1 on 2020-08-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200814_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='error.mp4', upload_to='videos'),
        ),
    ]
